function createaxes(Parent1, XData1, YData1)
%CREATEAXES(Parent1, XData1, YData1)
%  PARENT1:  axes parent
%  XDATA1:  line xdata
%  YDATA1:  line ydata

%  Auto-generated by MATLAB on 25-Nov-2025 13:18:29

% Create axes
axes1 = axes('Tag','DisplayAxes1_RealMag','Parent',Parent1);
hold(axes1,'on');

% Create line
line(XData1,YData1,'DisplayName','Transfer Fcn','Tag','DisplayLine1',...
    'Parent',axes1,...
    'LineJoin','chamfer',...
    'LineWidth',3.5,...
    'Color',[1 0.909803921568627 0.392156862745098]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0.414445371522381 2.39985866163583]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-0.0529770043996811 1.13130710924172]);
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'GridAlpha',0.3,'GridColor',...
    [0.850980392156863 0.850980392156863 0.850980392156863],'XColor',...
    [0.850980392156863 0.850980392156863 0.850980392156863],'YColor',...
    [0.850980392156863 0.850980392156863 0.850980392156863],'YTick',...
    [0 0.2 0.4 0.6 0.8 1 1.05]);
